go_import_path: hawx.me/code/retro
language: go

install:
  - make install

before_script:
  - touch config.toml
  - (cd app; npm rebuild node-sass)

script:
  - make
  - make test

notifications:
  email: false
