go_import_path: hawx.me/code/retro
language: go

install:
  - make install

before_script:
  - node --version
  - npm --version
  - touch config.toml
  - (cd app; npm rebuild node-sass)
  - npm i -g elm

script:
  - make
  - make test

notifications:
  email: false
